# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

processos_executados_tasks:
  description: >
    Buscar o status atualizado dos processos executados com sucesso, 
    via api: http://172.16.128.133:5678/webhook/execute-python?processo={nome}.

    Pergunta:
    {pergunta}

  expected_output: >
    Um resumo dos status de todos os processos executados com sucesso retornados pela api.
    Caso, haja um total de processos menor que 9 processos, verificar se algum dos processos deu erro na 
    monitoria, consultando a api: http://172.16.128.133:5678/webhook/execute-python?processo=processos_error
    Caso, processo sql-server/operation_history tenha sido executado com sucesso e com total de linhas maior que 100999, então,
    de uma otima noticia que processo mais critico esta ok.

processos_error_tasks:
  description: >
    Buscar o status atualizado dos processos com erro, 
    via api: http://172.16.128.133:5678/webhook/execute-python?processo=processos_error.

  expected_output: >
    Um resumo dos status de todos os processos retornados pela api que tiveram erro. 
    Caso, o total de processos com erros seja maior que 1 erros, alerta que precisa urgente verificar 
    os erros que podem afetar o portifolio.
